name: elixir
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

  format:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x

      - name: Checkout
        uses: actions/checkout@v1

      - name: Format
        run: mix format --check-formatted
  
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      redisgraph:
        image: redislabs/redisgraph:edge
        ports:
          - 6379:6379
    steps:
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x

      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      
      - name: Run Tests
        run: mix test
        
  dialyzer:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x

      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      
      - name: Cache dialyzer plt
        id: cache-plt
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-plt-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-plt-
      
      - name: Run Dialyzer
        run: mix dialyzer
